apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::677276082903:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-njFazvh6ftgR
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::677276082903:user/suresh
      username: suresh
    - groups:
      - expense-admin
      userarn: arn:aws:iam::677276082903:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-06T16:19:37Z"
  name: aws-auth
  namespace: kube-system
  uid: 8ec3ef3d-493e-4b7a-9250-0e7444c930d3