apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::677276082903:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-5OH4OY7sdezQ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::677276082903:user/suresh
      username: suresh
    - groups:
      - expense-admin
      userarn: arn:aws:iam::677276082903:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-11T17:34:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2200"
  uid: a1f2ddaa-7bb7-486a-8795-3846cd3c6d11